---
- name: Create apt keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx

- name: Add stork apt signing key
  ansible.builtin.apt_key:
    id: "{{ stork_apt_key_fingerprint }}"
    url: https://dl.cloudsmith.io/public/isc/stork/gpg.{{ stork_apt_key_fingerprint[-16:] }}.key
    keyring: /etc/apt/keyrings/stork.gpg
    state: present

- name: Add stork apt repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [signed-by=/etc/apt/keyrings/stork.gpg]
      https://dl.cloudsmith.io/public/isc/stork/deb/{{ ansible_distribution | lower }}
      {{ ansible_distribution_release }} main
    filename: stork
    update_cache: yes
    state: present
